### ISSUE TITLE
Undefined reference to yywrap in  src/mup/tools/doc/tr2html.c

### ISSUE THREAD

**Issue by azatsman** [muparkkra/mup#1130]
Did my best to verify that all the dependencies have been installed.
Ran 'make' after  running 'autoconf' and 'configre', got this from the linker:

gcc  -g -O2   -o tr2html tr2html.o  
/usr/bin/ld: tr2html.o: in function `input':
/bs/installs/src/mup/tools/doc/tr2html.c:3999: undefined reference to `yywrap'
/usr/bin/ld: tr2html.o: in function `yylex':
/bs/installs/src/mup/tools/doc/tr2html.c:3650: undefined reference to `yywrap'
collect2: error: ld returned 1 exit status

Relevant config data:

  gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  DISTRIB_DESCRIPTION="Linux Mint 20.2 Uma"
  Linux.... 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Output from 'autoconf':

configure.ac:12: installing './ar-lib'
configure.ac:10: installing './compile'
configure.ac:36: installing './config.guess'
configure.ac:36: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
lib/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
configure.ac: installing './ylwrap'

Output from '.configure':

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for grep that handles long lines and -e... /bin/grep
checking for a sed that does not truncate output... /bin/sed
checking for gs... /usr/bin/gs
checking for groff... /usr/bin/groff
checking for bison... /usr/bin/bison
checking for ppmtogif... /usr/bin/ppmtogif
checking for expr... /usr/bin/expr
checking for sort... /usr/bin/sort
checking for cat... /bin/cat
checking for egrep... /bin/egrep
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for pamtowinicon... none
checking for ppmtowinicon... /usr/bin/ppmtowinicon
checking for fltk-config... /usr/bin/fltk-config
checking for fl_alphasort in -lfltk... yes
checking for main in -lfltk_images... yes
checking for main in -lX11... yes
checking for XdbeQueryExtension in -lXext... yes
checking for XftDrawCreate in -lXft... yes
checking for XpmCreatePixmapFromData in -lXpm... yes
checking for XineramaIsActive in -lXinerama... yes
checking for jpeg_CreateCompress in -ljpeg... yes
checking for exp in -lm... yes
checking for png_read_info in -lpng... yes
checking for gzgets in -lz... yes
checking for xpmtoppm... /usr/bin/xpmtoppm
checking for ppmtopgm... /usr/bin/ppmtopgm
checking for i386-mingw32msvc-windres... none
checking how to run the C preprocessor... gcc -E
checking for egrep... (cached) /bin/egrep
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for uid_t in sys/types.h... yes
checking for unistd.h... (cached) yes
checking for working chown... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for access... yes
checking for alarm... yes
checking for atan... no
checking for cos... no
checking for getcwd... yes
checking for isascii... yes
checking for isspace... yes
checking for memcmp... yes
checking for memmove... yes
checking for memset... yes
checking for munmap... yes
checking for pow... no
checking for putenv... yes
checking for select... yes
checking for setenv... yes
checking for sin... no
checking for sqrt... no
checking for strcasecmp... yes
checking for strchr... yes
checking for strcmp... yes
checking for strcpy... yes
checking for strcspn... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strncpy... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for tan... no
checking for unlink... yes
checking for kill... yes
checking for sleep... yes
checking for waitpid... yes
checking for /usr/lib/libvga.a... no
checking for /usr/lib64/libvga.a... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating doc/manpages/Makefile
config.status: creating doc/htmldocs/Makefile
config.status: creating lib/Makefile
config.status: creating mup-input/Makefile
config.status: creating mup-input/examples/Makefile
config.status: creating mup-input/includes/Makefile
config.status: creating mup-input/testfiles/Makefile
config.status: creating mup-input/testfiles/test-midi/Makefile
config.status: creating packaging/Makefile
config.status: creating src/Makefile
config.status: creating src/include/Makefile
config.status: creating src/mup/Makefile
config.status: creating src/mkmupfnt/Makefile
config.status: creating src/mupprnt/Makefile
config.status: creating tools/Makefile
config.status: creating tools/mup/Makefile
config.status: creating tools/doc/Makefile
config.status: creating tools/test/Makefile
config.status: creating src/mupdisp/Makefile
config.status: creating tools/mupdisp/Makefile
config.status: creating src/mupmate/Makefile
config.status: creating tools/mupmate/Makefile
config.status: creating config.h
config.status: executing depfiles commands

**Comment by muparkkra** [comment]
Apparently something about your version of either autoconf or configure is not setting LEXLIB. The easiest fix is to simply supply a yywrap function. To fix, at the end of tr2html.l add:

int
yywrap()
{
        return(1);
}

We will add that in the next release.

**Comment by azatsman** [comment]
It works -- thank you!
   On Monday, January 24, 2022, 09:54:13 PM EST, muparkkra ***@***.***> wrote:  
 
 


Apparently something about your version of either autoconf or configure is not setting LEXLIB. The easiest fix is to simply supply a yywrap function. To fix, at the end of tr2html.l add:

int
yywrap()
{
return(1);
}

We will add that in the next release.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muparkkra** [comment]
Fixed in Mup 7.0
