### ISSUE TITLE
some command to allow page breaks  -- to be used in lengthy blocks

### ISSUE THREAD

**Issue by jasper-e** [muparkkra/mup#1135]
I would like to tell Mup where it could break lengthy blocks into new pages.

Theoretically I could start a new block but in practice it comes with adverse effects on vertical alignment.
For the moment I can only add a newpage and start a block manually. However when I insert content above, that means manual layout editing where the page breaks need to go -- I would like to make it automated, page break shall happen at the last allowed place.

**Comment by muparkkra** [comment]
In the User's Guide, in the section "Newscore and newpage, samescore and samepage", there is a trick involving "newscore scoresep = 0" which can be used to let a block be broken into pieces without getting white space between the pieces when on the same page. We believe that should already provide the functionality being requested. If you disagree, please provide more precise details of what additional functionality would still be desired.

**Comment by muparkkra** [comment]
Having received no reply after more than 10 days, we are assuming the proposed way to use existing functionality will meet what was requested, and are closing this issue.
