### ISSUE TITLE
Time signature changes and endings

### ISSUE THREAD

**Issue by ScouterAndy** [muparkkra/mup#1142]
I am attempting to typeset a score where there is a time signature change at the start of the first, second, and third ending.   Before any of the endings, the music is in 3/4 but changes to 4/4 at the start of the first, second, and third ending.   On the repeat, it goes through the section where it changes to 3/4 again, and then of course back to 4/4 in the second, and finally the third, ending.

The 4/4 is correctly typeset at the start of the first ending.   However, it needs to also be at the start of the second and the third ending, as the musician got there from the bar before the first ending, which is in 3/4.

Mup seems to refuse to typeset the time signature notation other than the first time, no matter how I specify it.

Each ending does have the time change notated:

**4: 4ecg-;ecg-;8ecg-;r;4r;
repeatend ending "2"
score
        time = 4/4
        beamstyle = 4,4,4,4
music
// second ending
1: 2c;8r;c;e;f;**

See example:

![mup-time-endings](https://user-images.githubusercontent.com/36800273/204338696-86fa9fd5-ad25-48b1-9243-e72884ce315c.png)

**Comment by muparkkra** [comment]
Just add a y after the time signature to force it to be printed:
   time=4/4y
As it says in the User's Guide:
  If followed by "y," the time signature will be printed even if it didn't change.

**Comment by muparkkra** [comment]
Note that an alternate approach could be to use invisbar to print the 4/4 before the first ending, to make it clearer that it applies to all subsequent endings. Here is a simple example that demonstrates that idea:
score
time=3/4
music
1: 2.c;
invisbar
score time=4/4
music
invisbar
bar ending "1."
1: 2c;;
repeatend ending "2";
1: 2c;;
repeatend ending "3."
1: 2c;;
bar

**Comment by ScouterAndy** [comment]
> Just add a y after the time signature to force it to be printed: time=4/4y As it says in the User's Guide: If followed by "y," the time signature will be printed even if it didn't change.

I guess that's the question of interpretation... I interpret it as the time signature DOES change in going from bar 8 (3/4) to bar 12 (4/4) which is what happens the second time through... or from bar 8 (3/4) to bar 13 (4/4) the third time through.

So in that way, it wouldn't need the 'y' because it does actually change (unless you simply read linearly and ignore the repeats).   That's why I didn't think to try the 'y' option.

However, I see the other interpretation (probably the one used in the code, which does work linearly from the top to the bottom of the mup source file) and therefore I see why it works with the 'y'.   And it does, with the 'y', do what I want (which was to place the 4/4 at the start of the second ending and at the start of the third ending).

I don't want to get into a debate about Gould versus Read and Ross as there is considerable disagreement on whether to notate time signature changes before the barline or after in the case of repeats!

**Comment by muparkkra** [comment]
Hello,

Thanks for confirming that using y did what you were looking for.

                        Bill and John           ***@***.***
                        Arkkra Enterprises      http://www.arkkra.com

**Comment by ScouterAndy** [comment]
Yes, it did.

As an aside... are you aware that all emails to support@ your website and the mup-users mailing list are being bounced?   Have tried from multiple email accounts on multiple email providers.   Tried to contact the domain contact for the site and that bounced as well.   Seems like GitHub is the only way to contact Arkkra support.

**Comment by muparkkra** [comment]
We are still receiving email at the site, so not "all" are being blocked. Our service provider has had to  tighten things a lot to avoid too many bad messages getting through. Note that only members are allowed to send to the mup-users list.
