### ISSUE TITLE
arithmetic in macros or wherever numbers can be used

### ISSUE THREAD

**Issue by muparkkra** [muparkkra/mup#667]
Allow arithmetic expression in macros or wherever numbers can be used. 

1. Integer constant expressions 

Now that additive time exists, strings like "2+8" have a special meaning in some contexts (half plus eighth), so you couldn't allow this to mean "10" in general. 

Today you have a special mode IF_CLAUSE in lex.l for parsing macro "if" clauses, and ifgram.y.  What if we had a syntax like 
	(( numeric_expression ))
and while inside of this you'd execute (almost) the same parsing code as for macro "if" clauses?  Except, of course, at the end, instead of the result being true or false, it would be a number.  (I used this notation to be like ksh and I think okay for Mup parsing, but this is just an example; maybe there's something better to use.)  Could lex.l be rigged up to return this as a T_NUMBER, just as if it had seen that literal number? You'd load up yytext with the ASCII digits of the answer.  It should handle negative answers, since you use atoi() on yytext in the "num" rule. Or have a new token for this. 

2. Floating point constant expressions 

One problem, though, is that for many of the reasons we might want expressions, we would want floating point.  So maybe you couldn't reuse the macro "if" code, but would have to copy and change it.  And I see that floats are not a token like T_NUMBER, but rather they are the nonterminal symbol "floatnum".  So you could have floatnum have the alternate rule of T_FLOATNUM, where that new token is one of these expressions. 

[ BTW, after I saw this I realized we today allow white space around the decimal point, which I could argue is not really right. ] 

If we support only one of int or float expressions, I think float may be more needed.  But really it should be both.  And it would be better if people didn't have to think about it and use two different syntaxes to invoke the two.  It could confuse non-computer-people.  Hmmm.  Well, the mini-parser could be equipped for floating point.  If the answer comes back equal to an integer, you stuff the ASCII version into yytext and return T_NUMBER.  Else, you sprintf(yytext, "%f", value) and return a new token which is in an alternate rule for floatnum.  If the answer equals an integer but the context requires a floatnum, the current first floatnum rule handles that. 

3. Expressions involving locations 

Constant expressions could have some uses, but the main uses of expressions I can think of involve locations.  (Like the arrow.)  One example I've mentioned before is a way to find the midpoint of a measure.  If you have bar line location tags =a and =b, I'd want to say:  (=a.x + =b.x) / 2.  But now I think I'm remembering a problem with all this; location tags' values aren't known until placement is done.  In this example I would be using this to print something and that would be okay; but in theory someone could try to use this result in a context where the answer is needed earlier. And the design above for constant expressions assumes everything is a constant, and known immediately.  Maybe it could be extended to allow variables, or at least querying parameter values (those that are numbers), but that doesn't help with location tags due to this timing problem. 

BTW, my example above ( (=a.x + =b.x) / 2 ) isn't quite right when you're on the first measure of a line.  You'd have to add some small number to the =a.x so that it would use the pseudo bar. 

Is the nonterminal symbol "location" the only place location tags are used? (I mean "read" not "set".)  I know they already allow some arithmetic. Maybe what is needed is, let the x and y components of "location" be general expression (as described above), and (only) in this context allow the use of location tags in these expressions.  But I think we don't need the full generality, as explained below: 

In a sense, the only sensible thing to do with two location tag values is to subtract them.  It's like C pointers.  So when I said 
	(=a.x + =b.x) / 2
the appropriate way to write it would be 
	=a.x + (=b.x - =a.x) / 2
analogous to what you would do with 2 C pointers to find the array element halfway between the two.  But I don't know if it make things any easier to say, the x or y of a "location" can't use tag any old way, but rather must have at most one "standalone" tag value, and all others must be in a pair that is subtracted.  I suppose the bottom line problem remains, that the expression would have to be stored and evaluated after placement phase is done. 

Well, today you have a compressed format for macro "if" expressions, which you parse later, though offhand I can't remember why that is.  In this case you could have a similar thing.  Or even, just store the input string of the "location" and do full parsing later.  Oh, maybe would be harder because you don't have one big yytext[] for the expression, but rather one token at a time.  Well, whatever is easiest. 

Come to think of it, today's INPCOORD sort of is a way of storing today's x and y expressions, isn't it.  It's just that will this feature you need a more general format. 

4. Summary 

I think the most useful thing would be to allow general expressions inside "location" x and y expressions, including arbitrary numbers of location tag references.  The expressions would be like in ifgram.y, but allowing floating point.  I guess we also have to continue to support today's "time" option. It could well also be useful to support a sqrt() "function".  Hopefully we don't need trigonometric functions, but then again it probably wouldn't be much harder. 

There's less priority to allow expressions elsewhere (by using "(( .... ))" syntax or something); and if we do allow that, I think it's fine to forbid usage of location tags there, so they could be evaluated immediately and the answer returned as a num or floatnum token.  If we do this part of the feature, we might want to consider allowing querying of (numeric) parameter values too. 

5. Example 

Here is a header file that people could include to draw an arrow.  Note that I didn't need trig functions, but I did need square root.  I think it's right, because I tested this first as C code that printed out the "line" statements. 
 
 //------------ header file "arrow" --------------- 
 // User must define the following macros: 
 //	STARTX and STARTY: coords of the start (base) of the arrow 
 //	ENDX and ENDY: coords of the end (tip) of the arrow 
 //	HEADLEN: length of the arrow head 
 //	HEADWID: width of the arrow head 
 // The coords will probably be based off of location tags, though they could 
 // be fixed numbers.  The arrow head dimensions will probably be fixed numbers. 
 // 
 // Then the user should include this file, and it will generate the statements 
 // to draw the arrow. 
 // 
 // This file can be included multiple times in a song.  Just redefine the 
 // variables listed above, and include again. 
  
 // intermediate calculations 
 undef FULLX	define	FULLX		((ENDX) - (STARTX)) @ 
 undef FULLY	define	FULLY		((ENDY) - (STARTY)) @ 
 undef FULLLEN	define	FULLLEN		(sqrt(FULLX * FULLX + FULLY * FULLY)) @ 
 undef COS	define	COS		(FULLX / FULLLEN) @ 
 undef SIN	define	SIN		(FULLY / FULLLEN) @ 
 undef HEADX	define	HEADX		(HEADLEN * COS) @ 
 undef HEADY	define	HEADY		(HEADLEN * SIN) @ 
 undef HBX	define	HBX		((ENDX) - HEADX) @ 
 undef HBY	define	HBY		((ENDY) - HEADY) @ 
 undef THICKLEN	define	THICKLEN	((HEADWID) / 2.0) @ 
 undef THICKX	define	THICKX		(THICKLEN * SIN) @ 
 undef THICKY	define	THICKY		(THICKLEN * COS) @ 
  
 // coords of end of feathers 
 undef FEATHUPX	define	FEATHUPX	(HBX - THICKX) @ 
 undef FEATHUPY	define	FEATHUPY	(HBY + THICKY) @ 
 undef FEATHDNX	define	FEATHDNX	(HBX + THICKX) @ 
 undef FEATHDNY	define	FEATHDNY	(HBY - THICKY) @ 
  
 line (STARTX, STARTY) to (ENDX, ENDY) 
 line (ENDX, ENDY) to (FEATHUPX, FEATHUPY) 
 line (ENDX, ENDY) to (FEATHDNX, FEATHDNY) 
 //---------------- end of example ------------------ 

If you wanted a filled-in triangle for the arrowhead instead of building the whole arrow (or whatever you're drawing) out of lines, however, it's a problem.  It would be nice to be able to define PostScript for a user symbol. You'd want to construct the PostScript string from fixed sections in double quotes, and plug numbers into it for positions etc. by using the "+" operator to combine them into one string.  So, we'd need syntax that would allow an expression containing location tags to become a string containing the number that is the answer.  But there may be problems.  When are the user symbols evaluted and stored?  If it's before the placement phase, we wouldn't have the answer yet.  Also, if someone wanted to draw several arrows, they'd have to make a separate symbol for each.  Well, I guess this stuff could happen in a macro taking parameters, or a file to be included multiple times, so that isn't the main problem.

**Comment by muparkkra** [comment]
This feature is less necessary, now that we know how to use user postscript to store a location variable and access it in a later user postscript. 

============================== Response ============================== 

This first part is mostly historical; see later part... 

I started thinking about arithmetic on tags. I had a brainstorm. This idea is still very very early, so it is still fuzzy, and I may realize it won't work, or at least it may change radically, but it seems promising... 

How about if we introduce a "set" statement, that allows you to create location tags that are based on arithmetic expressions involving other location tags and/or constants. The user has to specify the expressions for whatever subset of the 6 absolute c[] things they are going to reference. Or maybe we could have some rules for certain cases, like if they defined n and s but not y, we would assume y is in the middle, or if y but no n or s, we set n and s equal to y. 

Anyway, their input might be something like: 
 
  // create a new location tag named _foo that is halfway between 
  // tag a and tag b 
  set _foo = { 
	x = (b.x + a.x) / 2; 
	y = (b.y + a.y) / 2; 
  } 

They can then reference _foo like any other tag: 
  print (_foo.x, _foo.y) "X" 

This new tag type becomes a new main list object that gets filled in at parse time with the expression parse trees (up to 6 of them), and then is ignored until print phase.  It looks something like struct ARITH_COORD { 
	/* The user's expression to set each of the 12 things; 
	 * (well, actually only the 6 absolute ones) 
	 * pointer is 0 if they didn't set it */ 
	struct EXPRESSION * coord_expressions[NUM_COORD]; 
	/* The coord */ 
	float c[NUM_COORD]; 
	/* bit map of which values of c are valid, 
	 * to check if user referenced one without an expression  ?? */ 
	int calculated;
}; 

The _foo tag name would be mapped to the c[] in the appropriate struct. When print phrase hits one of these in the main list, it calculates the values by filling in c[] for each non-null expression. I think it should be able to resolve everything to an absolute location by then. If not, maybe it could generate PostScript to calculate it at PostScript time ?? 

When print phase hits a (x, y) thingie, if either the x or y refers to a location tag that is of this new kind, it will resolve to the appropriate c[] and work just like today. (Or maybe not quite like today, but hopefully something do-able.) 

If they set to a different value later, we just make another ARITH_COORD for each, and the name has to map to the "current" c[]. I _think_ that will work, but maybe not, and if not, maybe we only allow setting a given tag one time. 

Could be issues if the tags referenced in a set statement are associated with different staffs or scores. locvar.c is already hairy, and this could make it worse... 
 
---------- After discussing some more..... 

Today user can provide an arbitrary number of "offsets" which currently can only be constants that are added or subtracted. So expand that to allow multiply and divide, and various functions. The most useful function is something like 
	distance(_tag1.x, _tag2.x)
Questions: 
- Are these taken exactly as they are, or are they effective distances,
as if the music was all one long score? 
	- User could potentially want either one. 
	- If they are on separate pages, only effective distance 
	makes any kind of sense 
	- The most similar current thing uses effective distance
So I would propose two functions, eff_dist and true_dist. For true_dist, the multi-page case is a ufatal. 
- In a given *_dist() call, both arguments must be either
vertical or horizontal. 

Then there would be other functions, probably at least 
	sqrt 
	sin 
	cos 
	tan 
	atan 
	atan2
and maybe others. Things like log and exp seem dubious. Note that all of these listed above avoid the parsing thin ice. abs would fall through the ice, although absv or absval would work. 

Internally, maybe something like this: There would be new fields in INPCOORD: 
	struct EXPR_NODE *hor_expr_p; 
	struct EXPR_NODE *vert_expr_p
For today's style things, they would be null. At the appropriate time after placement and before use by printing, they would be evaluated, with the results placed in the existing hsteps or vsteps fields. So that means the functions must return results in stepsizes. We decided no special scaling is needed, since the coords themselves are already adjusted by staffscale when needed. 

Then: 
 struct CINFO { 
	float *coord_p;		/* points to a c[] array */ 
	short c_index;		/* RX, RY, etc */ 
 }; 
 
 struct EXPR_NODE { 
	int	op; 
	union { 
		struct EXPR_NODE *lchild_p; 
		struct CINFO coord; 
		double value; 
	} left; 
	union { 
		struct EXPR_NODE *rchild_p; 
		struct CINFO coord; 
	} right; 
 }; 

And op something like 
 /* binary operators */ 
 #define OP_BINARY	(0x10) 
 #define OP_ADD 	(OP_BINARY + 0) 
 #define OP_SUB	(OP_BINARY + 1) 
 #define OP_MUL	(OP_BINARY + 2) 
 #define OP_DIV	(OP_BINARY + 3) 
 #define OP_MOD	(OP_BINARY + 4) 
  
 /* Only EFF_DIST and TRUE_DIST take two tag c[] things rather than two direct 
  * numbers, so they get a separate classification. */ 
 #define OP_TAGC_BINARY	(0x20) 
 #define OP_EFF_DIST	(OP_TAGC_BINARY + 0) 
 #define OP_TRUE_DIST	(OP_TAGC_BINARY + 1) 
  
 /* unary operators */ 
 #define OP_UNARY	(0x40) 
 #define OP_SQRT	(OP_UNARY + 0) 
 #define OP_SIN	(OP_UNARY + 1) 
 #define OP_COS	(OP_UNARY + 2) 
 #define OP_TAN	(OP_UNARY + 3) 
 #define OP_UMINUS	(OP_UNARY + 4) 
  
 /* operands */ 
 #define OP_OPERAND	(0x80) 
 /* A literal number (int or float) would be converted to double 
  * and stored in left.value */ 
 #define OP_DOUBLE_LITERAL	(OP_OPERAND + 0) 
 /* A reference to a tag c[] thing (used as argument to distance() 
  * or absdistance()) would have the address of the appropriate c[] as 
  * its left.value_p */ 
 #define OP_DOUBLE_REF	(OP_OPERAND + 1) 

And then user can say insane things like 
  print (_foo.x + sqrt(distance(f.x, g.e) / cos(absdistance(h.s, q.n), 
	_win.n - sin(.3) * 7.4) "hi" 

=========================== Response to response =========================== 

I assume that distance(_tag1.x, _tag2.x) and absdistance(_tag1.x, _tag2.x) mean, from tag1 to tag2, not tag2 to tag1.  And so the answer could be negative.  And so:  distance(_tag1.x, _tag2.x) = - distance(_tag2.x, _tag1.x). 

And if that's true, I suggest a different name for absdistance, because that sounds like "absolute value", which is not what you mean.  Maybe directdistance, but that's pretty long.  It's probably worth providing this function, since it's actually easier to implement than distance(), right? 

I can't think of any reason to mix horizonal and vertical coords as args to either function.  If someone wants something to be proportional to something else, it would be some distance, not a single coord.  But certainly, you should be able to use dist(a.x,b.x) and dist(c.y,d.y) in the same expression.  I do it in the arrow example.  I square them, add, and sqrt to find the hypotenuse.  Well... okay, certainly for "absdistance"; maybe it's not so clear for "distance".  Still, I'd definitely allow it.  I think if the arrow crossed over a scorefeed this would make sense.  It would find the correct angle, and when you drew the hypotenuse (arrow), it would work, I think. 

Functions:  We've seen there's a need for sqrt, so it's probably not much harder to provide other similar ones, as you list.  I did a "man sin" to see the "see also" section.  This suggests, for trig, to have sin, cos, tan, asin, acos, atan, atan2.   atan2 is different in that it has two args, but it can be quite handy since it gets you into the correct quadrant.  To do certain things without atan2, you have to do atan and then have an "if" statement to adjust the results, but we don't have that.  (Well, we could have ?: to simulate an "if" ....). 

Maybe abs wouldn't be used too much.  And there is a workaround: 
        abs(x) == sqrt(x * x) 

I don't see a reason for log or exp, though.  Or any others I can think of. 

It's nice if you can parse this as part of the "main grammar".  Unlike ifgram.  But if you had to, you could have delimiters like ((....)) around these expressions. 

About scaling:  I'm sure "scale" should affect everything, and does, since it's applied magically by scaling the whole page, so the question is just "staffscale".  What do you do today with type B and C locvars, as listed in locvar.c?  (Not associated with a staff.)  I'm guessing you wouldn't apply staffscale.  Even if staffscale is set in the score context? Well, anyhow, I imagine these expressions should evaluate to a normal stepsize value; and then you scale that final result, or not, as you do today, according to your rules based on the main coordinate of this INPCOORD.  All the other coords must appear as args to distance() and there is no offset associated with them. 

Since DIST takes two tag c[] things, doesn't "right" also need to be a union of EXPR_NODE and value_p?  Or maybe it just points at another node, a leaf node....

**Comment by jasper-e** [comment]
Something like this is till necessary for dealing with song numbers.
some syntax like (( )) or \calc( ) etc. would be highly appreciated.
I would use it in a self-refining macro that increases the song number by one for example.

Then I could use it as part of a sef-redifining macro also to build table of contents...

**Comment by muparkkra** [comment]
Actually, this feature is already being implemented in the next release. There will be a new kind of macro,  where the value is determined by evaluating a numeric expression. This might be used for things like an automatically incrementing counter, or proportionally altering the values of multiple parameters by only changing a single factor.

There will also be a new string() function, which will map a number to a Roman numeral or letter for printing. In connection with the expression macros, this might be useful for something like labeling movements of a large work with Roman numerals, and being able to add another movement in the middle, with later movements getting renumbered automatically. It might also be useful for placing rehearsal marks at other than bar lines.

**Comment by muparkkra** [comment]
Implemented in 7.0 via new "eval" macros
